---
area:devices:
  - 'lss/devices/*'

area:sequencer:
  - 'lss/sequencer.py'
  - 'lss/pad.py'
  - 'lss/drums.py'

area:dev:
  - '.github/*'
  - '.gitignore'
  - '.pre-commit-config.yaml'
  - 'pyproject.toml'
  - 'setup.*'
